title: Kang Yeon Hyeong
description: Engineer
site_title: '@yhkang - yhkang1'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: yhkang0101
blog_url: https://yhkang0101.github.io
email: kyh940101@gmail.com
#keybase_username: yhkang
#twitter_username: yhkang_
#reddit_username: yhkang

# absolute or relative
profile_picture: assets/images/yhkang.jpg

# Google Analytics ID
google_analytics: 